-- MySQL Script generated by MySQL Workbench
-- Wed Jul 14 16:34:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nexedu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nexedu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nexedu` DEFAULT CHARACTER SET utf8 ;
USE `nexedu` ;

-- -----------------------------------------------------
-- Table `nexedu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nexedu`.`user` (
  `userid` VARCHAR(50) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nexedu`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nexedu`.`video` (
  `seqno` INT NOT NULL AUTO_INCREMENT,
  `userid` VARCHAR(50) NOT NULL,
  `subjectno` VARCHAR(100) NOT NULL COMMENT '강좌번호',
  `subject` VARCHAR(255) NOT NULL COMMENT '강좌명',
  `regdate` DATETIME NOT NULL DEFAULT now() COMMENT '동영상 데이터 수신일시',
  `createdate` DATETIME NULL COMMENT '동영상 생성일자',
  `processdate` DATETIME NOT NULL DEFAULT now() COMMENT '처리시간: 엔진에서 statusprocess 값이 변경될때마다 now() 값을 기록한다.',
  `filepathmov` VARCHAR(255) NOT NULL,
  `filepathstt` VARCHAR(255) NOT NULL,
  `statusprocess` TINYINT NOT NULL DEFAULT 0 COMMENT '동영상 처리에 대한 상태 정보\n\n0: 강좌동영상 정보 수신 완료\n1: 강좌동영상 데이터 수신 중\n2: 음성인식 수행 중\n3: 유사도 조사중\n4: 처리 완료',
  `statussimilarity` TINYINT NOT NULL DEFAULT 0 COMMENT '유사도에 대한 상태\n0: 미검토\n1: 신고(표절)\n2: 검토완료',
  `memo` TEXT NULL COMMENT '신고사유',
  `reporteruserid` VARCHAR(50) NULL COMMENT '신고자 아이디',
  `reporterdate` DATETIME NULL COMMENT '신고일시',
  PRIMARY KEY (`seqno`),
  INDEX `fk_movie_user1_idx` (`userid` ASC),
  INDEX `fk_video_user1_idx` (`reporteruserid` ASC),
  CONSTRAINT `fk_movie_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `nexedu`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_user1`
    FOREIGN KEY (`reporteruserid`)
    REFERENCES `nexedu`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nexedu`.`movie_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nexedu`.`movie_has_movie` (
  `seqno` INT NOT NULL,
  `seqnochld` INT NOT NULL,
  `similaritytime` VARCHAR(255) NULL,
  `similarityrange` TEXT NULL,
  PRIMARY KEY (`seqno`, `seqnochld`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nexedu`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nexedu`.`account` (
  `userid` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT '비밀번호',
  `isaccountnonexpired` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '계정의 만료여부(1:만료되지 않음, 0:만료)',
  `isaccountnonlocked` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '계정이 잠겨 있는지 여부를 리턴(1: 계정잠기지 않음, 0: 계정잠김)',
  `iscredentialsnonexpired` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '계정의 패스워드 만료여부(1:만료되지 않음, 0:만료됨)',
  `isenabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '계정이 사용가능한지 여부(1:사용가능, 0:사용불가능)',
  `authority` ENUM('ROLE_ADMIN', 'ROLE_USER') NOT NULL COMMENT 'ROLE_USER, ROLE_ADMIN 등의 권한',
  INDEX `fk_userauth_user1_idx` (`userid` ASC),
  PRIMARY KEY (`userid`),
  CONSTRAINT `fk_userauth_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `nexedu`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nexedu`.`videosimilarity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nexedu`.`videosimilarity` (
  `seqno` INT NOT NULL COMMENT '원본 동영상(강좌) seqno',
  `seqnotarget` INT NOT NULL COMMENT '비교 동영상(강좌)의 seqno',
  `similarityrange` TEXT NOT NULL COMMENT '동영상의 같은 시간의 영역대를 구한값을 , 로 구분하여 저장',
  PRIMARY KEY (`seqno`, `seqnotarget`),
  INDEX `fk_movie_has_movie1_movie2_idx` (`seqnotarget` ASC),
  INDEX `fk_movie_has_movie1_movie1_idx` (`seqno` ASC),
  CONSTRAINT `fk_movie_has_movie1_movie1`
    FOREIGN KEY (`seqno`)
    REFERENCES `nexedu`.`video` (`seqno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_movie1_movie2`
    FOREIGN KEY (`seqnotarget`)
    REFERENCES `nexedu`.`video` (`seqno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
